






<h1 class="text-center">Gallery</h1>

<br>


<section  class="row">
<?php foreach ($pictures as $pic) : ?>

<article class="col-12 col-sm-6 col-md-4">
  <div  class="card mb-3" data-aos="fade-up">
  <a href="<?= "?page=detail&id=".$pic['id'] ?>">
    <img src="<?= $pic['src'] ?>" class="card-img-top" class="img-fluid" width="550px" height="550px" alt="<?= $pic['title'] ?>">
  </a>
    <div class="card-body" data-aos="fade-down">
    <a class="text-dark text-decoration-none" href="<?= "?page=detail&id=".$pic['id'] ?>">
      <h4 class="card-title"><?= $pic['title'] ?></h4>
    </a>
      <p class="card-text"><?= $pic['description'] ?></p>
      <p class="card-text"><?= $pic['author'] ?></p>
      <a href="<?= "?page=detail&id=".$pic['id'] ?>" class="btn btn-secondary">En savoir davantage</a>
    </div>
  </div>
</article>

<?php endforeach ?>
</section>
 
<script>





</script>




    </div>





    </article>
    




 <!--$pic['id'] = va récupérer id de la table, $pic['title'] récupère le titre de de la table...-->
 <!--boucle foreach pour récupérer tous les éléments de $pictures

