<h1 class="mb-3 text-center">Admin Delete</h1>

<form method="POST">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input type="text" class="form-control" name="title" id="title" placeholder="Title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <input type="text" class="form-control" name="description" id="description" placeholder="Description">
</div>
<div class="mb-3">
  <label for="src" class="form-label">Source</label>
  <input type="text" class="form-control" name="src" id="src" placeholder="URL Source">
</div>
<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input type="text" class="form-control" name="author" id="author" placeholder="Author">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-primary" name="Delete" value="Delete">
</div>
</form>

































ire à remplir pour effectuer une suppression, car normalement, la suppression d'une image serait déclenchée par un simple bouton ou un lien sans nécessiter de saisir des données. -->
