<h1 class="mb-3 text-center">LOGIN</h1>

<br>

<?php

if (isset($error)) {


  echo $error;

}



?>


<br><br>

<form method="POST">


<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email</label>
    <input type="email" class="form-control" name="mail" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Mot de passe</label>
    <input type="password" class="form-control" name="password" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>


  </div>
  <button type="submit" class="btn btn-primary" id="login" name="submit">Se connecter</button>
</form>



<script>

const connectionConfirmation = document.getElementById("login");

connectionConfirmation.addEventListener("click", () => alert("Bienvenu, vous êtes dorénavant connecté !"));


        </script>























