

    <h1 class="mb-3 text-center"><?= $pictures['title'] ?></h1>

<section class="row" >

    <div class="text-center">
    <img src="<?= $pictures['src'] ?>"  width="650px" height="650px" alt="<?= $pictures['title'] ?>">
</div>





    <div class="mb-3 text-center col-12 mt-3 fst-italic font-weight-light">

    <?= $pictures['title'] ?>

  


    </div>



    <div class="text-center col-12 mt-3 fst-italic font-weight-light">

    <br><br>
        

    <?= $pictures['description'] ?>
        

    </div>



    <div class="mb-3 text-center col-12 mt-3 fst-italic font-weight-light">

    <?= $pictures['author'] ?>
        
    </div>


    </section>





