<h1 class="mb-3 text-center">Admin Update</h1>

<form method="POST">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input type="text" class="form-label" value="<?= $pictures["title"]?>" class="form-control" name="title" id="title" placeholder="Title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <input type="text" value="<?= $pictures["description"]?>" class="form-control" name="description" id="description" placeholder="Description">
</div>
<div class="mb-3">
  <label for="src" class="form-label">Source</label>
  <input type="file"value="<?= $pictures["src"]?>"  class="form-control" name="src" id="src" placeholder="URL Source">
</div>
<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input type="text" value="<?= $pictures["author"]?>" class="form-control" name="author" id="author" placeholder="Author">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-primary" name="Update" value="Update">
</div>
</form>





































formulaire sont préremplis avec les informations actuelles de l'image, ce qui permet à l'utilisateur de les modifier et de soumettre le formulaire pour effectuer la mise à jour. -->
