<h1 class="mb-3 text-center">REGISTER</h1>

<br>

<form method="POST">


<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Prénom</label>
    <input type="text" class="form-control" name="firstName" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">Vos informations ne seront partagées à aucun tiers.</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nom</label>
    <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">Vos informations ne seront partagées à aucun tiers.</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Adresse email</label>
    <input type="email" class="form-control" name="mail" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">Vos informations ne seront partagées à aucun tiers.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Mot de passe</label>
    <input type="password" class="form-control" name="password" id="exampleInputPassword1">
  </div>
  </div>
  <button type="submit" class="btn btn-primary" name="submit">Soumettre</button>
</form>


























   9. **`<button type="submit" class="btn btn-primary" name="submit">Soumettre</button>`** :
      - Cette ligne crée un bouton de soumission du formulaire. L'attribut "type" est "submit", ce qui signifie que lorsque l'utilisateur clique sur ce bouton, le formulaire sera soumis au serveur. La classe "btn btn-primary" donne un aspect stylisé au bouton. L'attribut "name" est "submit", ce qui permet d'identifier ce bouton lors de la soumission du formulaire.

   En résumé, ce code HTML génère un formulaire d'inscription avec des champs pour le prénom, le nom, l'adresse e-mail et le mot de passe, ainsi qu'un bouton de soumission. Le formulaire est stylisé à l'aide des classes CSS pour une apparence propre. Des messages d'aide sont également fournis pour informer l'utilisateur de la confidentialité de ses informations. Lorsque l'utilisateur soumet ce formulaire, les données seront envoyées au serveur pour traitement ultérieur. -->
